#pragma once

#include <concepts>
#include <functional>
#include <initializer_list>
#include <vector>

#include "utils/db/db_interface.h"
#include "utils/tuple.h"
#include "utils/types.h"


template <IsDbTuple DbTuple>
class DbRam : public IDb<DbTuple> {
private:
    using InnerType = std::vector<DbTuple>;

public:
    //--------------------------------------------------------------------------
    // constructors/destructors

    DbRam() = default;

    /**
     * copy `db` from `startIndex` (inclusive) to `endIndex` (exclusive).
     */
    DbRam(const DbRam& db, bigint startIndex, bigint endIndex);

    /**
     * initialize a `DbRam` with the raw values in the brace-enclosed initializer list `initList`.
     */
    DbRam(std::initializer_list<DbTuple> initList);

    // note: special constructors like copy and move assignment constructors not written
    // since the autogenerated ones should do a per-member copy/move assignment/etc.,
    // which means they use the default `std::vector` ones already

    //--------------------------------------------------------------------------
    // `IDb`

    void clear() override;
    void push_back(const DbTuple& dbTuple) override;

    DbTuple operator [](bigint index) const override;

    void shuffle() override;
    void sort(const std::function<bool(bigint index1, bigint index2)>& compare) override;

private:
    InnerType vec;
};
