#pragma once

#include <concepts>
#include <cstdint>
#include <functional>
#include <initializer_list>
#include <vector>

#include "utils/db/db_interface.h"
#include "utils/tuple.h"


template <IsDbTuple DbTuple>
class DbRam : public IDb<DbTuple> {
private:
    using InnerType = std::vector<DbTuple>;

public:
    //--------------------------------------------------------------------------
    // constructors/destructors

    DbRam() = default;

    /**
     * copy `db` from `startIndex` (inclusive) to `endIndex` (exclusive).
     */
    DbRam(const DbRam& db, int64_t startIndex, int64_t endIndex);

    /**
     * initialize a `DbRam` with the raw values in the brace-enclosed initializer list `initList`.
     */
    DbRam(std::initializer_list<DbTuple> initList);

    // note: special constructors like copy and move assignment constructors not written
    // since the autogenerated ones should do a per-member copy/move assignment/etc.,
    // which means they use the default `std::vector` ones already

    //--------------------------------------------------------------------------
    // `IDb`

    void clear() override;
    void push_back(const DbTuple& dbTuple) override;
    int64_t size() const override;
    bool empty() const override;

    DbTuple operator [](int64_t index) const override;

    void shuffle() override;
    void sort(const std::function<bool(int64_t index1, int64_t index2)>& compare) override;

private:
    InnerType vec;

//------------------------------------------------------------------------------
// iterator

private:
    using Iter      = InnerType::iterator;
    using ConstIter = InnerType::const_iterator;

public:
    // non-const iterators
    Iter begin() {
        return this->vec.begin();
    }

    Iter end() {
        return this->vec.end();
    }

    // const iterators
    ConstIter begin() const {
        return this->vec.begin();
    }

    ConstIter end() const {
        return this->vec.end();
    }
};
