#pragma once

#include <openssl/evp.h>

#include "utils/ustring.h"


namespace Constants {


// lengths are in bytes
static constexpr int KEY_LEN         = 256 / 8;
static constexpr int IV_LEN          = 128 / 8;
static constexpr int BLOCK_SIZE      = 128 / 8;
static constexpr int HASH_OUTPUT_LEN = 512 / 8;
static const EVP_CIPHER* ENC_CIPHER  = EVP_aes_256_cbc();
static const EVP_MD* HASH_FUNC       = EVP_sha512();


} // namespace `Constants`


ustring genKey(int keyLen);
ustring genIv(int ivLen);


ustring hash(const EVP_MD* hashFunc, int hashOutputLen, const ustring& input);
ustring prf(const ustring& key, const ustring& input);


ustring encrypt(const EVP_CIPHER* cipher, const ustring& key, const ustring& ptext, const ustring& iv = ustring());

/**
 * pad `ptext` to `targetLenBytes` before encrypting.
 *
 * IMPORTANT: for some reason padding to exactly n blocks generates n + 1 blocks, so always pad to one less byte!
 */
ustring padAndEncrypt(
    const EVP_CIPHER* cipher, const ustring& key, const ustring& ptext, const ustring& iv, int targetLenBytes
);

ustring decrypt(const EVP_CIPHER* cipher, const ustring& key, const ustring& ctext, const ustring& iv = ustring());

/**
 * remove trailing padding generated by `padAndEncrypt()` after decrypting.
 */
ustring decryptAndUnpad(const EVP_CIPHER* cipher, const ustring& key, const ustring& ctext, const ustring& iv);
