#pragma once


#include <openssl/evp.h>

#include "utils.h"


ustring genKey(int keyLen);
ustring genIv(int ivLen);


ustring hash(const EVP_MD* hashFunc, int hashOutputLen, const ustring& input);
ustring prf(const ustring& key, const ustring& input);


ustring encrypt(const EVP_CIPHER* cipher, const ustring& key, const ustring& ptext, const ustring& iv = ustring());

/**
 * Pad `ptext` to `targetLenBytes` before encrypting.
 *
 * IMPORTANT: for some reason padding to exactly n blocks generates n + 1 blocks, so always pad to one less byte!
 */
ustring padAndEncrypt(
    const EVP_CIPHER* cipher, const ustring& key, const ustring& ptext, const ustring& iv, int targetLenBytes
);
ustring decrypt(const EVP_CIPHER* cipher, const ustring& key, const ustring& ctext, const ustring& iv = ustring());

/**
 * Remove trailing padding generated by `padAndEncrypt()` after decrypting.
 */
ustring decryptAndUnpad(const EVP_CIPHER* cipher, const ustring& key, const ustring& ctext, const ustring& iv);
