#pragma once

#include <openssl/evp.h>

#include "utils/types/ustring.h"


namespace utils::crypto {


// lengths are in bytes
inline constexpr int KEY_LEN         = 256 / 8;
inline constexpr int IV_LEN          = 128 / 8;
inline constexpr int BLOCK_SIZE      = 128 / 8;
inline constexpr int HASH_OUTPUT_LEN = 512 / 8;
inline const EVP_CIPHER* ENC_CIPHER  = EVP_aes_256_cbc();
inline const EVP_MD* HASH_FUNC       = EVP_sha512();


ustring genKey(int keyLen = KEY_LEN);
ustring genIv(int ivLen = IV_LEN);


ustring hash(
    const ustring& input, const EVP_MD* hashFunc = HASH_FUNC, int hashOutputLen = HASH_OUTPUT_LEN
);
ustring prf(const ustring& key, const ustring& input);


ustring encrypt(
    const ustring& key, const ustring& ptext, const ustring& iv = ustring(),
    const EVP_CIPHER* cipher = ENC_CIPHER
);

/**
 * pad `ptext` to `targetLen` before encrypting.
 *
 * IMPORTANT: for some reason padding to exactly n blocks generates n + 1 blocks,
 * so always pad to one less byte!
 */
ustring padAndEncrypt(
    const ustring& key, ustring ptext, const ustring& iv, int targetLen,
    const EVP_CIPHER* cipher = ENC_CIPHER
);


ustring decrypt(
    const ustring& key, const ustring& ctext, const ustring& iv = ustring(),
    const EVP_CIPHER* cipher = ENC_CIPHER
);

/**
 * remove trailing padding generated by `padAndEncrypt()` after decrypting.
 */
ustring decryptAndUnpad(
    const ustring& key, const ustring& ctext, const ustring& iv,
    const EVP_CIPHER* cipher = ENC_CIPHER
);


} // namespace `utils::crypto`
